name: Add/update Submodule in gh-pages

on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: string
      source_repo:
        description: 'GCWeb or wet-boew'
        required: true
        type: string

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo with submodules
        uses: actions/checkout@v4
        with:
          ref: gh-pages   # explicitly checkout gh-pages
          fetch-depth: 0  # fetch full history so git can push back
          submodules: false

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add or update submodule
        env:
          BRANCH_NAME: ${{ inputs.source_repo }}-pr${{ inputs.pr_number }}
        run: |
          if [ -d "$BRANCH_NAME" ]; then
            echo "Submodule exists. Updating..."
            git submodule update --init --remote "$BRANCH_NAME"
          else
            echo "Adding submodule..."
            git submodule add -b "$BRANCH_NAME" https://github.com/tristandasilva/wet-boew-demos.git "$BRANCH_NAME"
          fi

      - name: Commit changes
        run: |
          ls
          git add .
          git commit -m "Update or add submodule in gh-pages" --allow-empty
          git push origin gh-pages
